name: CI

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - python-version: 3.7
            toxenv: py37
          - python-version: 3.7
            toxenv: py37-nopandas
          - python-version: 3.8
            toxenv: py38
          - python-version: 3.8
            toxenv: py38-nopandas
          - python-version: 3.9
            toxenv: py39
          - python-version: 3.9
            toxenv: py39-nopandas
          - python-version: 3.10
            toxenv: py310
          - python-version: 3.10
            toxenv: py310-nopandas
          - python-version: 3.11
            toxenv: py311
          - python-version: 3.11
            toxenv: py311-nopandas

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install tox
        run: pip install tox

      - name: Run tests
        run: tox -e ${{ matrix.toxenv }}
